### ISSUE TITLE
Rack 2.x compatibility

### ISSUE THREAD

**Issue by rorymckinley** [grantspeelman/clickatell-catcher-rack#1]
hey @grantspeelman - this line causes issues when running with Rack 2.0 [https://github.com/grantspeelman/clickatell-catcher-rack/blob/master/lib/clickatell/catcher/rack.rb#L2](url).

It looks like the file has been renamed to null_logger. Happy to submit a patch - but I was just wondering if you would be happy to break compatibility with older rack versions (the simplest option).

**Comment by grantspeelman** [comment]
looking into it, will see if it's simple enough to keep compatibility

**Comment by grantspeelman** [comment]
@rorymckinley you should be good to go 👍

**Comment by rorymckinley** [comment]
Thanks for the rapid response @grantspeelman - 0.1.1 works like a charm.
